// ทั้ง 4 เว็บไซต์ใช้ Apps Script Web App URL เดียวกัน
const API_URL = 'PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE';
const TEACHER_URL = 'PASTE_YOUR_TEACHER_WEBSITE_URL_HERE';
const STUDENT_URL = 'PASTE_YOUR_STUDENT_WEBSITE_URL_HERE';
